image: python:3.6.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install .
          - pytest -vv --integration --cov
